---
engines:
  rubocop:
    enabled: true
    checks:
      Rubocop/Style/FrozenStringLiteralComment:
        enabled: false
      Rubocop/Style/Documentation:
        enabled: false
      Rubocop/Style/ClassAndModuleChildren:
        enabled: false
