---
AllCops:
  DisplayCopNames:    true
  DisplayStyleGuide:  true
  StyleGuideCopsOnly: true
  TargetRubyVersion:  2.3

Style/Lambda:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
